<?php

/**
 * Implements hook_form_alter().
 */
function isa_block_highlighted_circle_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, ['block_content_highlighted_circle_form', 'block_content_highlighted_circle_edit_form'])) {
    $form['field_image']['#states'] = [
      'visible' => [
        ':input[name="field_link_block_variant"]' => ['value' => 'imagen']
      ]];

    $form['field_icon']['#states'] = [
      'visible' => [
        ':input[name="field_link_block_variant"]' => ['value' => 'icon']
      ]];

    $form['#validate'][] = 'isa_block_highlighted_circle_validate';

  }
}

/**
 * Custom validation function.
 */
function isa_block_highlighted_circle_validate(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $variant = $form_state->getValue('field_link_block_variant');
  if ($variant[0]['value'] == 'imagen') {
    $image = $form_state->getValue('field_image')[0];
    if (!count($image['fids'])) {
      $form_state->setErrorByName('', 'La imagen es obligatoria.');
    }
  }

  if ($variant[0]['value'] == 'icon') {
    $icon = $form_state->getValue('field_icon')[0];
    if(!$icon['icon']) {
      $form_state->setErrorByName('', 'La icono es obligatoria.');
    }
  }

}
