stages:
  - build
  - build-image
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: none

build_composer:
  stage: build
  script:
    - |-
        TARGET=tag
        if [ "${CI_COMMIT_REF_NAME}" = "develop" ]; then
          TARGET=branch
        fi

        curl -k --show-error --fail --header "Job-Token: $CI_JOB_TOKEN" \
             --data ${TARGET}=${CI_COMMIT_REF_NAME} \
             "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/composer"
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
  tags:
    - ssh
