<?php

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements FORM_ALTER.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function isa_block_library_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (str_starts_with($form_id, 'block_content_')) {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = '_isa_block_library_callback_submit';
      }
    }
  }
}

function _isa_block_library_callback_submit($form, FormStateInterface $form_state) {
  $form_state->setRedirect('view.isa_block_library.page_1');
}
