<?php

/**
 * Implements hook_library_info_alter().
 */
function isa_magnific_popup_library_info_alter(&$libraries, $extension) {
  if(isset($libraries['magnific_popup'])){
    $libraries['magnific_popup']['js'] = [
      'js/magnific-popup.js' => [],
      '//cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js' => []
    ];

    $libraries['magnific_popup']['css']['base'] = [
      '//cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css' => []];
  }
}
