isa_site_config.settings:
  type: config_object
  label: 'OpenID Connect Nimble settings'
  mapping:
    webfom_emails:
      type: sequence
      label: 'List of Webforms-Emails'
      sequence:
        type: mapping
        label: 'Item Webform-Email'
        mapping:
          webform:
            type: string
            label: 'Webform id'
          email:
            type: string
            label: 'Email id'
