<?php
/**
 * @file
 * Contains the definition of isa_block_slider.
 */


/**
 * {@inheritDoc}
 *
 * Implements hook_preprocess_block().
 */
function isa_block_slider_preprocess_block(&$variables) {

  if (isset($variables['elements']['#derivative_plugin_id'])) {
    $uuid = $variables['elements']['#derivative_plugin_id'];

    /** @var Drupal\block_content\Entity\BlockContent $block */
    $block = Drupal::service('entity.repository')->loadEntityByUuid('block_content', $uuid);

    if ($block) {
      if ($block->bundle() == 'slider') {
        $contents = $block->get('field_images_list');
        $entities = $contents->referencedEntities();

        $contentsProcess = [];
        /** @var Drupal\paragraphs\Entity\Paragraph $entity */
        foreach ($entities as $entity) {

          $description = $entity->get('field_description')->value;

          /** @var \Drupal\file\Entity\File $image */
          $image = $entity->get('field_image');

          $imageUrl = '';
          $title = '';
          $alt = '';
          if ($image) {
            $imageUrl = \Drupal::service('file_url_generator')
              ->generateString($image->entity->getFileUri());
            $title = $image->title;
            $alt = $image->alt;
          }

          $url = '';
          if($entity->get('field_link') && $entity->get('field_link')->first() && $entity->get('field_link')->first()->getUrl()){
            $url = $entity->get('field_link')->first()->getUrl()->toString();
          }

          /** @var \Drupal\file\Entity\File $image */
          $imageMobile = $entity->get('field_image_mobile');

          $imageMobileUrl = '';
          $titleMobile = '';
          $altMobile = '';
          if ($imageMobile && $imageMobile->entity) {
            $imageMobileUrl = \Drupal::service('file_url_generator')
              ->generateString($imageMobile->entity->getFileUri());
            $titleMobile = $image->title;
            $altMobile = $image->alt;
          }

          $item = [
            'description' => $description,
            'image_title' => $title,
            'image_alt' => $alt,
            'image_url' => $imageUrl,
            'url' => $url,
            'image_mobile_title' => $titleMobile,
            'image_mobile_alt' => $altMobile,
            'image_mobile_url' => $imageMobileUrl,
          ];
          array_push($contentsProcess, $item);
        }

        $variables['content']['items'] = $contentsProcess;
      }
    }
  }
}

/**
 * Implements hook_theme().
 *
 * {@inheritdoc}
 */
function isa_block_slider_theme() {
  return [
    'block__content__slider' => [
      'template' => 'block--content--slider',
      'base hook' => 'block',
    ],
  ];
}
